### ISSUE TITLE
Replace all metadata or normalizedmetadata?

### ISSUE THREAD

**Issue by davidvaccaro** [chafey/dicomweb-update-spec#1]
Hey Chris, Looks like a good proposal to me... one point I noticed:

----

Update all Study Instances - PATCH to /studies/[id]/metadata

Body is an array of [JSON documents](https://github.com/chafey/dicomweb-update-spec/blob/main/docs/updateSchema.md) for each instance in the study of attributes to update and remove
All instance JSON documents shall have the same change for attributes at the patient/study/level. An error is thrown otherwise
PatientId can be changed
Attempting to set Study UID, Series UID or SOP InstanceUID will generate an error

----

Did you intend this endpoint to be PATCH all study instances given a payload of typical DICOMweb "metadata" or your new proposed "normalizedmetadata" ?

**Comment by chafey** [comment]
This is intended to be an atomic full study update without having to supply the ENTIRE metadata (study metadata can be huge)

**Comment by davidvaccaro** [comment]
But your proposed spec reads exactly "PATCH to /studies/[id]/metadata" ... was that intentional? Seems like it should have been:

**PATCH to /studies/[id]/normalizedmetadata**

**Comment by chafey** [comment]
There is a patch for nomalizedmetadata (just study attributes) as well as the the entire study metadata (everything)

**Comment by davidvaccaro** [comment]
OK. I see... I thought I caught a minor typo of "metadata" when you intended "normalizedmetadata".
