### ISSUE TITLE
Are the Move APIs too STOW-RS like?

### ISSUE THREAD

**Issue by davidvaccaro** [chafey/dicomweb-update-spec#2]
All the APIs seem pretty clear except for the Move APIs. They look a little STOW-RS like... can you explain more the concept of this set of proposed APIs?

For example:

----

Move Study to a new or existing Patient - POST to /studies/[id]

Body is a DICOM dataset of attributes
Body must include new PatientID
Body may include a new Study Instance UID
If patient does not exist, it will be created using attributes from the prior patient

---- 

How does this differ from STOW-RS POST /studies/{study} ?  I think I get the general idea that these MOVE APIs would be used to groom up an existing dataset moving series, instances and even whole studies around patients but can you clarify the payload (plain old DICOM data?) and if there is any overlap with existing STOW-RS transactions?

**Comment by chafey** [comment]
These APIs are intended to support merge/split operations.  So if you have two studies you want to merge/combine, you could move all series from study A into study B.  Likewise, you could move specific instances from one series to another series, in the same study or another study.  If the target patient/study/series does not exist, it will create them using attributes from the prior patient/study/series

**Comment by chafey** [comment]
I will be writing examples with unit tests, you can see a few here (most are stubbed out currently):
https://github.com/chafey/dicomweb-update-spec/blob/main/test/move-study.test.js
https://github.com/chafey/dicomweb-update-spec/blob/main/test/move-series.test.js
https://github.com/chafey/dicomweb-update-spec/blob/main/test/move-instance.test.js

**Comment by davidvaccaro** [comment]
But does your API endpoint signature (and payload) duplicate the same signature of one of the STOW-RS endpoints? 

Yours: 

**POST /studies/[id] (POST of DICOM dataset)**

STOW-RS: 

**POST /studies/{study}  (POST of DICOM dataset)**

**Comment by chafey** [comment]
Ahh yes it accidently conflicts with STOW-RS.  Ill pick another endpoint thank you!

**Comment by davidvaccaro** [comment]
Sure thing... looks like a very worthy effort you have going here.
